In [1]:
import cv2

# For USB webcam (index 0 = first camera)
cap = cv2.VideoCapture(0)


while True:
    ret, frame = cap.read()
    if not ret:
        break

    cv2.imshow("Camera Stream", frame)

    if cv2.waitKey(1) & 0xFF == ord("q"):
        break

cap.release()
cv2.destroyAllWindows()

ModuleNotFoundError: No module named 'cv2'

In [4]:
import cv2

# For USB webcam (index 0 = first camera)
cap = cv2.VideoCapture(0)


while True:
    ret, frame = cap.read()
    if not ret:
        break

    cv2.imshow("Camera Stream", frame)

    if cv2.waitKey(1) & 0xFF == ord("q"):
        break

cap.release()
cv2.destroyAllWindows()

ModuleNotFoundError: No module named 'cv2'

In [3]:
!pip install opencv-python


In [5]:
import cv2

# For USB webcam (index 0 = first camera)
cap = cv2.VideoCapture(0)


while True:
    ret, frame = cap.read()
    if not ret:
        break

    cv2.imshow("Camera Stream", frame)

    if cv2.waitKey(1) & 0xFF == ord("q"):
        break

cap.release()
cv2.destroyAllWindows()

ModuleNotFoundError: No module named 'cv2'

In [6]:
import cv2


ModuleNotFoundError: No module named 'cv2'

In [7]:
!pip install opencv-contrib-python


   ---------------------------------------- 0.0/45.3 MB ? eta -:--:--
   ---------------------------------------- 0.5/45.3 MB 3.7 MB/s eta 0:00:12
   - -------------------------------------- 1.6/45.3 MB 4.2 MB/s eta 0:00:11
   --- ------------------------------------ 3.7/45.3 MB 6.4 MB/s eta 0:00:07
   ----- ---------------------------------- 5.8/45.3 MB 7.3 MB/s eta 0:00:06
   ------- -------------------------------- 8.4/45.3 MB 8.3 MB/s eta 0:00:05
   --------- ------------------------------ 11.0/45.3 MB 9.1 MB/s eta 0:00:04
   ----------- ---------------------------- 13.4/45.3 MB 9.3 MB/s eta 0:00:04
   ------------- -------------------------- 15.5/45.3 MB 9.4 MB/s eta 0:00:04
   ---------------- ----------------------- 19.1/45.3 MB 10.3 MB/s eta 0:00:03
   ------------------- -------------------- 22.5/45.3 MB 10.9 MB/s eta 0:00:03
   ---------------------- ----------------- 25.4/45.3 MB 11.2 MB/s eta 0:00:02
   ------------------------- -------------- 28.3/45.3 MB 11.3 MB/s eta 0:0

In [8]:
import cv2

# For USB webcam (index 0 = first camera)
cap = cv2.VideoCapture(0)


while True:
    ret, frame = cap.read()
    if not ret:
        break

    cv2.imshow("Camera Stream", frame)

    if cv2.waitKey(1) & 0xFF == ord("q"):
        break

cap.release()
cv2.destroyAllWindows()

ModuleNotFoundError: No module named 'cv2'

In [11]:
import cv2

# For USB webcam (index 0 = first camera)
cap = cv2.VideoCapture(0)


while True:
    ret, frame = cap.read()
    if not ret:
        break

    cv2.imshow("Camera Stream", frame)

    if cv2.waitKey(1) & 0xFF == ord("q"):
        break

cap.release()
cv2.destroyAllWindows()

ModuleNotFoundError: No module named 'cv2'

In [12]:
import cv2
print(cv2.__version__)


ModuleNotFoundError: No module named 'cv2'

In [16]:
!  pip install opencv-python


In [ ]:
import cv2

# For USB webcam (index 0 = first camera)
cap = cv2.VideoCapture(0)


while True:
    ret, frame = cap.read()
    if not ret:
        break

    cv2.imshow("Camera Stream", frame)

    if cv2.waitKey(1) & 0xFF == ord("q"):
        break

cap.release()
cv2.destroyAllWindows()

In [ ]:
import cv2
print(cv2.__version__)


4.12.0


In [ ]:
import cv2

# Read image
img = cv2.imread(r"C:\Users\DELL\OneDrive\springboard\dummy_salary_slip.png")

if img is None:
    print("Error: Could not read image.")
else:
    # Flip vertically (0), horizontally (1), or both (-1)
    flip_vertical = cv2.flip(img, 0) #0 is for vertical flip
    flip_horizontal = cv2.flip(img, 1) #1 for horizontal flip
    flip_both = cv2.flip(img, -1) #-1 for both

    # Show results
    cv2.imshow("Original", img)
    cv2.imshow("Flipped Vertically", flip_vertical)
    cv2.imshow("Flipped Horizontally", flip_horizontal)
    cv2.imshow("Flipped Both", flip_both)

    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [ ]:
import cv2

# Load an imageC:\Users\DELL\OneDrive\springboard\dummy_salary_slip.png
img = cv2.imread(r"C:\Users\DELL\OneDrive\springboard\dummy_salary_slip.png")   # Replace with your file path

# Check if the image loaded correctly
if img is None:
    print("Error: Could not read image.")
    exit()

# Resize image (width=300, height=300)
resized = cv2.resize(img, (300, 300))

# Show both
cv2.imshow("Original", img)
cv2.imshow("Resized", resized)

# Wait for a key press
cv2.waitKey(0)
cv2.destroyAllWindows()

# Optional: Save the resized image
cv2.imwrite("resized_output.jpg", resized)

In [1]:
import cv2

# Load an image
img = cv2.imread(r"C:\Users\DELL\OneDrive\springboard\dummy_salary_slip.png")   # Replace with your file path

# Check if image loaded correctly
if img is None:
    print("Error: Could not read image.")
    exit()

# Convert to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Show both
cv2.imshow("Original", img)
cv2.imshow("Grayscale", gray)

# Wait until a key is pressed
cv2.waitKey(0)
cv2.destroyAllWindows()

# Optional: Save grayscale image
cv2.imwrite("grayscale_output.jpg", gray)

True

In [1]:
import cv2

# Load an image
img = cv2.imread(r"C:\Users\DELL\OneDrive\springboard\dummy_salary_slip.png")   # Replace with your file path

# Check if image loaded correctly
if img is None:
    print("Error: Could not read image.")
    exit()

# Apply Gaussian Blur (15x15 kernel) mostly prefer odd number 
#as kernel size. More the size of kernel more stronger blur
#less the no of size less stronger the kernel
blur = cv2.GaussianBlur(img, (15, 15), 0)

# Show both
cv2.imshow("Original", img)
cv2.imshow("Blurred", blur)

# Wait for key press
cv2.waitKey(0)
cv2.destroyAllWindows()

# Optional: Save the blurred image
cv2.imwrite("blurred_output.jpg", blur)

True

In [5]:
#CODE 8

import cv2
import numpy as np

img = np.zeros((500, 500, 3), dtype="uint8")

# Draw shapes
cv2.line(img, (0, 0), (500, 500), (255, 0, 0), 5)
cv2.rectangle(img, (50, 50), (200, 200), (0, 255, 0), 3)
cv2.circle(img, (300, 300), 80, (0, 0, 255), -1)

# Add text
cv2.putText(img, r"C:\Users\DELL\OneDrive\springboard\dummy_salary_slip.png", (50, 400), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2)

cv2.imshow("Shapes and Text", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
#CODE 9

import cv2

img = cv2.imread(r"C:\Users\DELL\OneDrive\springboard\dummy_salary_slip.png", 0)  # Load in grayscale

_, thresh = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)

cv2.imshow("Original", img)
cv2.imshow("Thresholded", thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
#CODE 9

import cv2

img = cv2.imread(r"C:\Users\DELL\OneDrive\springboard\dummy_salary_slip.png", 0)  # Load in grayscale

_, thresh = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)

cv2.imshow("Original", img)
cv2.imshow("Thresholded", thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
#CODE 10

import cv2

img = cv2.imread(r"C:\Users\DELL\OneDrive\springboard\dummy_salary_slip.png", 0)

edges = cv2.Canny(img, 100, 200)

cv2.imshow("Edges", edges)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
import numpy as np

# Creating 1D and 2D arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[10, 20, 30], [40, 50, 60]])

print("1D Array:", arr1)
print("2D Array:\n", arr2)

1D Array: [1 2 3 4 5]
2D Array:
 [[10 20 30]
 [40 50 60]]


In [3]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Data type:", arr.dtype)

Shape: (2, 3)
Dimensions: 2
Size: 6
Data type: int64


In [4]:
import numpy as np

zeros = np.zeros((2, 3))
ones = np.ones((3, 2))
range_arr = np.arange(0, 10, 2)
space_arr = np.linspace(0, 1, 5)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Arange:", range_arr)
print("Linspace:", space_arr)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]


In [5]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print("Element at (0,1):", arr[0, 1])
print("2nd Row:", arr[1, :])
print("3rd Column:", arr[:, 2])
print("Slice (2x2):\n", arr[:2, :2])

Element at (0,1): 20
2nd Row: [40 50 60]
3rd Column: [30 60 90]
Slice (2x2):
 [[10 20]
 [40 50]]


In [6]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Square:", a ** 2)

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]
Square: [100 400 900]


In [7]:
import numpy as np

arr = np.array([5, 10, 15, 20])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))

Sum: 50
Mean: 12.5
Median: 12.5
Standard Deviation: 5.5901699437494745
Max: 20
Min: 5


In [8]:
import numpy as np

m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

print("Element-wise Multiplication:\n", m1 * m2)
print("Matrix Multiplication:\n", np.dot(m1, m2))
print("Transpose:\n", m1.T)

Element-wise Multiplication:
 [[ 5 12]
 [21 32]]
Matrix Multiplication:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]


In [9]:
import numpy as np

np.random.seed(0)
print("Random Integers:\n", np.random.randint(1, 10, (2, 3)))
print("Random Floats:\n", np.random.rand(2, 3))
print("Normal Distribution:\n", np.random.randn(5))

Random Integers:
 [[6 1 4]
 [4 8 4]]
Random Floats:
 [[0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504]]
Normal Distribution:
 [ 2.54520078  1.08081191  0.48431215  0.57914048 -0.18158257]


In [10]:
import numpy as np

arr = np.array([5, 10, 15, 20, 25])
mask = arr > 12

print("Array:", arr)
print("Mask:", mask)
print("Filtered:", arr[mask])

Array: [ 5 10 15 20 25]
Mask: [False False  True  True  True]
Filtered: [15 20 25]


In [11]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum (axis=0):", np.sum(matrix, axis=0))
print("Sum (axis=1):", np.sum(matrix, axis=1))
print("Mean (axis=0):", np.mean(matrix, axis=0))
print("Cumulative Sum:", np.cumsum(matrix))

Sum (axis=0): [5 7 9]
Sum (axis=1): [ 6 15]
Mean (axis=0): [2.5 3.5 4.5]
Cumulative Sum: [ 1  3  6 10 15 21]


In [12]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
vector = np.array([10, 20, 30])

print("After Broadcasting:\n", arr + vector)

After Broadcasting:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [13]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Vertical Stack:\n", np.vstack((a, b)))
print("Horizontal Stack:\n", np.hstack((a, b)))

arr = np.arange(10)
split = np.array_split(arr, 3)
print("Splitted Arrays:", split)

Vertical Stack:
 [[1 2 3]
 [4 5 6]]
Horizontal Stack:
 [1 2 3 4 5 6]
Splitted Arrays: [array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [14]:
import numpy as np

A = np.array([[2, 1], [1, 3]])
B = np.array([8, 18])

X = np.linalg.solve(A, B)

print("Matrix A:\n", A)
print("Vector B:", B)
print("Solution X:", X)

Matrix A:
 [[2 1]
 [1 3]]
Vector B: [ 8 18]
Solution X: [1.2 5.6]


In [15]:
import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60]])

# Save array
np.save("my_array.npy", arr)

# Load array
loaded = np.load("my_array.npy")

print("Original Array:\n", arr)
print("Loaded Array:\n", loaded)

Original Array:
 [[10 20 30]
 [40 50 60]]
Loaded Array:
 [[10 20 30]
 [40 50 60]]


In [16]:
import numpy as np

arr = np.array([12, 5, 7, 2, 9])

print("Original:", arr)
print("Sorted:", np.sort(arr))
print("Indices that would sort:", np.argsort(arr))
print("Search position for 6:", np.searchsorted(arr, 6))

Original: [12  5  7  2  9]
Sorted: [ 2  5  7  9 12]
Indices that would sort: [3 1 2 4 0]
Search position for 6: 2


In [17]:
!pip install plotly

In [21]:
import plotly.express as px

data = {
    "Year": [2018, 2019, 2020, 2021, 2022],
    "Sales": [100, 150, 130, 170, 180]
}

fig = px.line(data, x="Year", y="Sales", title="Sales Growth Over Years")
fig.show()

ModuleNotFoundError: No module named 'plotly'

In [19]:
!pip show plotly

Name: plotly
Version: 5.24.1
Summary: An open-source, interactive data visualization library for Python
Home-page: https://plotly.com/python/
Author: Chris P
Author-email: chris@plot.ly
License: MIT
Location: C:\Users\DELL\anaconda3\Lib\site-packages
Requires: packaging, tenacity
Required-by: 


In [20]:
import sys
print(sys.executable)


c:\Users\DELL\AppData\Local\Programs\Python\Python313\python.exe


In [22]:
!{sys.executable} -m pip install plotly


   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.8 MB 13.6 MB/s eta 0:00:01
   --------------------------- ------------ 6.8/9.8 MB 19.2 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 17.5 MB/s eta 0:00:00

   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [n

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [26]:
!python.exe -m pip install --upgrade pip


   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----------------------- ---------------- 1.0/1.8 MB 7.4 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 7.1 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 25.1.1
    Uninstalling pip-25.1.1:
      Successfully uninstalled pip-25.1.1


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [27]:
import plotly.express as px

data = {
    "Year": [2018, 2019, 2020, 2021, 2022],
    "Sales": [100, 150, 130, 170, 180]
}

fig = px.line(data, x="Year", y="Sales", title="Sales Growth Over Years")
fig.show()

NotImplementedError: Attempting to convert data_frame of type <class 'dict'> to pandas DataFrame, but Pandas is not installed. Convert it to supported dataframe type or install pandas.

In [28]:
!{sys.executable} -m pip install pandas
!{sys.executable} -m pip install numpy
!{sys.executable} -m pip install plotly



  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   --- ------------------------------------ 1.0/11.0 MB 15.2 MB/s eta 0:00:01
   ------------------- -------------------- 5.2/11.0 MB 16.8 MB/s eta 0:00:01
   --------------------------------- ------ 9.2/11.0 MB 17.2 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 15.9 MB/s  0:00:00
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)

   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- ---------------------

In [30]:
import plotly.express as px

data = {
    "Year": [2018, 2019, 2020, 2021, 2022],
    "Sales": [100, 150, 130, 170, 180]
}

fig = px.line(data, x="Year", y="Sales", title="Sales Growth Over Years")
fig.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

In [31]:
!{sys.executable} -m pip install nbformat



   ---------------------------------------- 0/7 [fastjsonschema]
   ----------- ---------------------------- 2/7 [attrs]
   ----------- ---------------------------- 2/7 [attrs]
   ----------------- ---------------------- 3/7 [referencing]
   ----------------- ---------------------- 3/7 [referencing]
   ---------------------------- ----------- 5/7 [jsonschema]
   ---------------------------- ----------- 5/7 [jsonschema]
   ---------------------------- ----------- 5/7 [jsonschema]
   ---------------------------- ----------- 5/7 [jsonschema]
   ---------------------------- ----------- 5/7 [jsonschema]
   ---------------------------------- ----- 6/7 [nbformat]
   ---------------------------------- ----- 6/7 [nbformat]
   ---------------------------------- ----- 6/7 [nbformat]
   ---------------------------------- ----- 6/7 [nbformat]
   ---------------------------------- ----- 6/7 [nbformat]
   ---------------------------------------- 7/7 [nbformat]



  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [1]:
import plotly.express as px

data = {
    "Year": [2018, 2019, 2020, 2021, 2022],
    "Sales": [100, 150, 130, 170, 180]
}

fig = px.line(data, x="Year", y="Sales", title="Sales Growth Over Years")
fig.show()

In [2]:
import plotly.express as px

data = {
    "Height": [150, 160, 170, 180, 190],
    "Weight": [55, 60, 70, 80, 90],
    "Gender": ["F", "F", "M", "M", "M"]
}

fig = px.scatter(data, x="Height", y="Weight", color="Gender", title="Height vs Weight by Gender")
fig.show()

In [3]:
import plotly.express as px

data = {
    "Category": ["A", "B", "C", "D"],
    "Revenue": [120, 300, 180, 250]
}

fig = px.bar(data, x="Category", y="Revenue", title="Revenue by Category", color="Category")
fig.show()

In [4]:
import plotly.express as px

data = {
    "Fruit": ["Apple", "Banana", "Grapes", "Orange"],
    "Quantity": [30, 15, 25, 20]
}

fig = px.pie(data, names="Fruit", values="Quantity", title="Fruit Market Share")
fig.show()

In [5]:
import plotly.express as px

data = {
    "Country": ["India", "USA", "Canada", "Germany", "Australia"],
    "GDP": [3.7, 25.5, 2.2, 4.9, 1.8]
}

fig = px.choropleth(data, locations="Country", locationmode="country names",
                    color="GDP", title="World GDP (Trillions USD)",
                    color_continuous_scale="Viridis")
fig.show()

C:\Users\DELL\AppData\Local\Temp\ipykernel_15592\1873291058.py:8: DeprecationWarning:

The library used by the *country names* `locationmode` option is changing in an upcoming version. Country names in existing plots may not work in the new version. To ensure consistent behavior, consider setting `locationmode` to *ISO-3*.



In [6]:
import plotly.express as px
import numpy as np

data = np.random.randn(500)

fig = px.histogram(data, nbins=20, title="Random Data Distribution")
fig.show()

In [7]:
import plotly.express as px

data = {
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Finance"],
    "Salary": [40, 60, 55, 70, 45, 65]
}

fig = px.box(data, x="Department", y="Salary", title="Salary Distribution by Department")
fig.show()


In [8]:
import plotly.graph_objects as go

years = [2018, 2019, 2020, 2021, 2022]
sales = [100, 150, 130, 170, 180]
profit = [20, 30, 25, 35, 40]

fig = go.Figure()
fig.add_trace(go.Scatter(x=years, y=sales, mode='lines+markers', name='Sales'))
fig.add_trace(go.Scatter(x=years, y=profit, mode='lines+markers', name='Profit'))

fig.update_layout(title="Sales and Profit Over Time", xaxis_title="Year", yaxis_title="Value")
fig.show()

In [9]:
import plotly.express as px
import numpy as np

z = np.random.rand(5, 5)
fig = px.imshow(z, text_auto=True, color_continuous_scale="Plasma", title="Random Heatmap")
fig.show()

In [10]:
import plotly.express as px
import numpy as np

df = {
    "x": np.random.rand(50),
    "y": np.random.rand(50),
    "z": np.random.rand(50),
    "color": np.random.randint(0, 10, 50)
}

fig = px.scatter_3d(df, x="x", y="y", z="z", color="color", title="3D Scatter Plot Example")
fig.show()